### ISSUE TITLE
Support for Business Central Apps

### ISSUE THREAD

**Issue by FSharpCSharp** [dotnet/sign#173]
It would be desirable to support Business Central Apps. These are either *.navx or *.app files, which must also be signed for publication. Therefore a usage on this platform would be very desirable.

More about this and how the standard signing process works can be found [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sign-extension).

**Comment by onovotny** [comment]
I don't do a lot with Dynamics, so I don't have any experience with these file types. Are there some unsigned and signed files I can use for testing?

**Comment by onovotny** [comment]
From the link:

> Make sure that you sign the .app file on a computer that has Dynamics 365 Business Central installed.

As it's also using SignTool, this makes it sounds like Dynamics is registering a SIP. We would need that file along with redistribution rights for it if it's not part of some free-to-download SDK.

**Comment by FSharpCSharp** [comment]
I once attached a file like this from Microsoft. In the zip file is an app file, which was signed by the above mentioned way.

[Microsoft_Any.zip](https://github.com/dotnet/SignService/files/4117173/Microsoft_Any.zip)

**Comment by ShadowXVII** [comment]
> From the link:
> 
> > Make sure that you sign the .app file on a computer that has Dynamics 365 Business Central installed.
> 
> As it's also using SignTool, this makes it sounds like Dynamics is registering a SIP (an Authenticode signing plugin). We would need that file along with redistribution rights for it if it's not part of some free-to-download SDK.

Yes, it is. @freddydk

**Comment by freddydk** [comment]
Adding @aholstrup1
