### ISSUE TITLE
ARM deployment template doesn't match bitness of Azure Pipelines build

### ISSUE THREAD

**Issue by andrewmolyneux** [dotnet/sign#270]
After deploying Azure resources according to the documentation (invoking the "Deploy" command in Visual Studio on the ArmDeploy project) and building/deploying SignService using Azure Pipelines, I got this error when I first attempted to connect to the service:
![image](https://user-images.githubusercontent.com/5108077/89643576-f8015480-d8ad-11ea-9ca6-830d29b40da8.png)
I was able to resolve this by changing "Platform" to "64-bit" on the "General settings" tab of the "Configuration" blade for the App Service, but presumably either `azure-pipelines.server.yml` should build a 32-bit app, or `azuredeploy.json` should deploy the App Service with the platform set to 64-bit?

**Comment by clairernovotny** [comment]
azuredeploy.json should be updated...

**Comment by andrewmolyneux** [comment]
Thanks Claire, I think that's the fastest response I've ever received after posting an issue 😄
I'd offer to submit a PR for that but my knowledge of ARM templates is rudimentary.
