### ISSUE TITLE
VSIX broken after signing

### ISSUE THREAD

**Issue by tom-englert** [dotnet/sign#294]
In my projects I use a file named `LICENSE`, without file extension. This file is part of the VSIX container.
After signing the extension it is no longer installable; the VSIX installer complains `Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException: The package does not contain the software license agreement that is specified in the extension manifest (License).`

Investigating the differences I found that the signing changed the `[Content_Types].xml` inside the VSIX file; however it did not just add the needed extensions for signature files, but also removed the override for the license file:

![image](https://user-images.githubusercontent.com/10229954/93000824-1e5c8480-f52b-11ea-98dc-c819ee8ac1c6.png)

Removing this `Override` entry from the unsigned package leads to the same error message, so this seems to be the root cause.

**Comment by clairernovotny** [comment]
Can you please file this over at https://github.com/vcsjones/OpenOpcSignTool? That's the library that's doing the VSIX signing. 

In the interim, can you work around this by renaming the license file to add a file extension?

**Comment by clairernovotny** [comment]
Maybe a dup of https://github.com/vcsjones/OpenOpcSignTool/issues/76?

**Comment by tom-englert** [comment]
Yes, that seems to be the root cause. 
For now I have just renamed the file inside VSIX to *.txt, so that's not a blocker.

**Comment by dtivel** [comment]
@clairernovotny thinks this is fixed, but we need to verify the fix has flowed into this repo.

**Comment by dtivel** [comment]
The fix has flowed into this repo.  When @javierdlg copied source files in https://github.com/dotnet/sign/pull/650, it was from a point in time that included the fix.  For example, [this change](https://github.com/vcsjones/OpenOpcSignTool/pull/77/files#diff-2135a9563cf370aaf9f1138fb50996a8526c8bd111f75c98092ebacb1b6431aaL89-L93) is reflected [here](https://github.com/dotnet/sign/blob/1df56d5c09b004fec6b5413dc6c61183553589ec/src/Sign.Core/Tools/VsixSignTool/OpcPackage.cs#L89) in this repo.
