### ISSUE TITLE
Change to 'asmv2:publisher' value breaks one-click update process

### ISSUE THREAD

**Issue by LDXChrisS** [dotnet/sign#412]
Probably an oddball scenario here, but we have a widely installed one-click application that was previously signed 'manually' and the value assigned to 'asmv2:publisher' now differs to what we get when using the SignClient tool. This breaks the one-click check for updates process and actually blocks access to the application forcing the user to uninstall/re-install.

Our application is in use in scenarios where the end user often does not have permissions to uninstall/install, but previously they would at least have been able to 'skip' the update and inform their IT department that an update is required.

Alas, we cannot revert back to the old 'manual' signing process, the new world is Jenkins and AWS/Azure.

Our proposal is to allow the setting of this field to a value supplied by an optional parameter which would override the default behaviour where it is currently being taken from the signing certificate details. Whilst we could do this as a local change, it could be of benefit to other users when identities on certificates change. We would certainly be willing to make this change and submit a PR for it.

Thanks for your consideration

**Comment by dtivel** [comment]
This should be fixed with the new option to set publisher name.
