### ISSUE TITLE
Signed code contains invalid certificate chain 

### ISSUE THREAD

**Issue by yowl** [dotnet/sign#426]
Hi,

This is probably not related to SignService, but I'm posting here in case someone knows how I should go about solving this.

I had a code signing cert from Digicert which I used in an Azure pipeline to sign an appx.  This has been working well for the last year - thanks for the tool!

I recently renewed the cert and installed the new certificate in the KeyVault, and updated the user in the Users tab in the signservice web frontend to use the new cert and ran the pipeline to sign some code.  I downloaded the appx and it wont install on Windows 10 or 11.  The message in the popup is:
```
This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)
```
So I checked the properties on the appx and looked at the Digital Signatures tab where I see my cert.   I can click "Details" on there to see the countersignatures where I see the Digicert signer:
![image](https://user-images.githubusercontent.com/2720041/171227393-d6c6c556-be4e-4a7c-aa01-783b3ccdeaaa.png)

Which appears to have a problem - "root certificate which is not trusted by the trust provider".  I can then look at the details of that certificate and the path where, clicking on the root gives:
![image](https://user-images.githubusercontent.com/2720041/171226568-29fa8892-c3a7-42c2-aad9-6997b5be3b29.png)

So that looks ok doesn't it?   

If I compare signed code with the old cert against signed code with the new cert I see this difference in the advanced tabs (old on the left).
![image](https://user-images.githubusercontent.com/2720041/171229962-28acf10b-7038-4d5f-a2b3-4530c0437709.png)
The issuer on the renewed cert is our CN, not Digicert - is that important?

**Comment by clairernovotny** [comment]
Based on the error message, it looks like the root certificate isn't trusted by the machine. Closing this issue due to age.
