### ISSUE TITLE
Changes in Issuing OV Code Signing Certificate After June 1st, 2023

### ISSUE THREAD

**Issue by FSharpCSharp** [dotnet/sign#430]
There will be some adjustments or tightening in the future with the creation or delivery of code signing certificates. I have collected some information about this here.

From my point of view, these affect this project most severely. Is there a plan and / or solution for this? Unfortunately, I have been able to find nothing at all on this topic while browsing the issues.

[Here](https://www.ssl2buy.com/wiki/changes-issuing-ov-code-signing-certificate) are some general information about the topic. That's where the title of the issue comes from.

And here is a mail from a certificate vendor, which also informs about the changes.

> You may have seen a previous Sectigo communication announcing CA Browser (CA/B) Forum changes to its regulations for code signing certificates. You may be pleased to hear that the CA/B Forum has pushed its deadline for implementation to June 1, 2023.
> 
> The CA/B Forum has updated its regulations for code signing certificates and services, requiring all Certificate Authorities to obtain assurances that customers generate and protect their private keys in a secure HSM (Hardware Security Module).
> 
> This change from the CA/B Forum aims to reduce the potential misuse of code signing certificates and to further protect those certificates from getting into the wrong hands.
> 
> The deadline for implementation of the new regulations has been extended to June 1, 2023.
> 
> In order to comply with the new regulations, customers will no longer determine how and where the private key for the certificate is stored. Instead, Sectigo OV code signing certificates will be installed on an HSM and shipped securely to customers.
> 
> The extension of the deadline means that users can still purchase standard Code Signing Certificates from Sectigo for now. In order to comply with the CA/B Forum regulations Sectigo will transition to the HSM based certificates. We will provide you with more details about Sectigo’s cutoff date as it gets closer to the CA/B Forum’s deadline next year.
> 
> If you purchased a standard code signing certificate that still needs to be validated and issued by your organization, you should complete issuance before the existing certificate order is canceled next year in compliance with the new CA/B Forum requirements .

In a user forum that deals with the signing of app files in the area of "Microsoft Dynamics 365 Business Central", the following summary was written on this topic, which I would like to pass on directly:

> Thanks to everyone contributing to this discussion. If I understand correctly, the problem is not that we need EV certificates in the future, but that also OV certificates will still exist, but must be protected in Hardware. The issuer has to make sure he follows all the new rules and one of them is to make sure that the private key is stored securely in a device that is FIPS-140 Level 2 (or similar) compliant. That could be an HSM on the users side for example. Or everything is stored on the issuers side and you get a USB dongle needed to get access to the Private key stored on the issuers side.
> 
> For us, who need automation in our processes and nothing runs on "bare metal" anymore, but in VMs, a USB dongle might be a hurdle. But if I got it right, having a HSM ourselves could still work. I just scratched the surface on HSMs, but it seems many manufacturers have APIs or ready ot use software to access HSMs over the Network in one way or another, which might be handy for automatic signing of code from within a self-hosted runner (Github) / agent (Azure DevOps). At least it sounds easier to me than to make a USB dongle available to a VM hosting a runner / agent somewhere.
> 
> But if the user (we) have our own HSM, from what I understand, the issuers have to make sure you are actually using an HSM. That might require an audit in some form and it is easier for the issuers to host the keys themselves, I guess. In the end, I think it depends how the issuers implement their new issuing processes and if self-hosted HSMs are an option for us or not. As soon as some kind of hardware dongle is needed that is plugged into a physical device, I think all automation goes overboard.
> 
> On the other hand, HSMs can be very expensive, but I just found out that do not necessarily have to (YubiHSM 2 FIPS for example looks pretty affordable, being still in the 3-digit range).
> 
> You provided excellent information and articles here and my takeaway is, that we have to wait a little bit longer until the first issuers have their new processes implemented and from there we can see what options we have in the future.

I would be happy if you could continue to use this project, also with regard to the changes.

**Comment by clairernovotny** [comment]
Hi @FSharpCSharp,

We are aware of the upcoming changes and are working on some options to handle it.

**Comment by skindogz** [comment]
These changes are now in effect and this is exactly the scenario I'm stuck with. We have a code signing certificate in Azure KeyVault and can not find a tool to connect to use the certificate that also supports signing `.app` files specifically for Microsoft Dynamics 365 Business Central as mentioned above. 

Are there any updates on support for signing this type of file?

**Comment by jozefizso** [comment]
As our certificate for open source project expired, what are our options here? We are unable to get PFX certificates anymore and we go back years ago to local signing using an USB token... This does not work for open source projects and transparency.

**Comment by clairernovotny** [comment]
@skindogz the latest version supports signing Dynamics Business Central files.

@jozefizso This repo is for the sign cli tool. We don't issue certificates. The .NET Foundation does provide code signing certificates for .NET Foundation projects.

**Comment by jozefizso** [comment]
@clairernovotny But how is this tool usable now when all the certificates must be on physical disk?
