### ISSUE TITLE
NuGet signing fails with Azure Code Signing (ACS) timestamping service

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/sign#539]
When using `http://timestamp.acs.microsoft.com/` as the timestamp server for a NuGet package, I get an error:

`NuGet [C:\Users\cnov\AppData\Local\Temp\w5ye15cg.0dn\lk52ym3x.nupkg]: NU3018: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
fail: Sign.Core.INuGetSignTool[0]`

That warning seems to be in error as it also warns with DigiCert's timestamp url of `http://timestamp.digicert.com`

`warn: Sign.Core.INuGetSignTool[0]
      NuGet [C:\Users\cnov\AppData\Local\Temp\q3n5cejc.vto\tx11bc4y.nupkg]: NU3018: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.`

**Comment by dtivel** [comment]
I wasn't able to reproduce that behavior.  If you can provide detailed repro steps, including information about your OS and whether or not the relevant root certificates are trusted on your machine outside of this signing context.

Note:  I hit https://github.com/dotnet/runtime/issues/79935, which blocks use of the ACS timestamping service in NuGet package signing.

**Comment by dtivel** [comment]
https://github.com/dotnet/runtime/pull/80209

**Comment by dtivel** [comment]
https://www.nuget.org/packages/System.Security.Cryptography.Pkcs/7.0.1 has the fix.

https://github.com/dotnet/runtime/tree/0a2bda10e81d901396c3cff95533529e3a93ad47/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs
