### ISSUE TITLE
Cannot overwrite signature on already signed NuGet package

### ISSUE THREAD

**Issue by dtivel** [dotnet/sign#547]

**Comment by clairernovotny** [comment]
Isn't there a --force parameter? Does that work or is it broken?

**Comment by dtivel** [comment]
Yes, [the draft CLI spec proposes a `--force` parameter](https://github.com/dotnet/sign/blob/dtivel/cli-spec/docs/cli-spec.md); however:

* The option isn't currently implemented.
* The preview Sign CLI is supposed to match behavior of its predecessor. The old SignService [overwrote signatures by default with no opt-out](https://github.com/dotnet/sign/blob/34f0acefee3673ba192ae0f72e39d029d4d2ef78/src/SignService/SigningTools/NuGetSignService.cs#L126) and [so does Sign CLI](https://github.com/dotnet/sign/blob/b85082906e9c4706efb7580009fe9ebbc320a335/src/Sign.Core/Tools/NuGetSignTool.cs#L45).
* The default, which is to overwrite, is broken.
