### ISSUE TITLE
Question: Authenticode, HSM & ClickOnce

### ISSUE THREAD

**Issue by RhomGit** [dotnet/sign#588]
Hi, I am trying to use a USB HSM issued by a CA (Yubikey) and am trying to EV sign ClickOnce files but can't get it working.

Is this project strictly related to Azure Key Vault signing only? My CA apparently doesn't support EV code signing via Azure Key Vault: https://www.ssl.com/how-to/code-signing-with-azure-key-vault/
You seem to support EV code signing of ClickOnce files via Azure Key Vault. If so, is there specific CA's that support this?

**Comment by dtivel** [comment]
Currently, yes, this project is related to Azure Key Vault signing only; however, we are interested in supporting other HSM's.

I can't recommend specific CA's for integrating with Azure Key Vault.  You'd need to reach out to a specific CA to see if they support it.
