### ISSUE TITLE
Use Azure SDK's RSA implementation

### ISSUE THREAD

**Issue by dtivel** [dotnet/sign#649]
With https://github.com/Azure/azure-sdk-for-net/pull/33186 merged, we should use Azure SDK's `RSA` implementation instead of https://github.com/novotnyllc/RSAKeyVaultProvider.

CC @clairernovotny

**Comment by clairernovotny** [comment]
The azure sdk version with the functionality is stable and we should migrate to it: https://www.nuget.org/packages/Azure.Security.KeyVault.Keys
