### ISSUE TITLE
Have a setting to disable call to mage or add more parameters

### ISSUE THREAD

**Issue by klamfeldt** [dotnet/sign#682]
**Is your feature request related to a problem? Please describe.**
When signing files some properties are updated with wrong value by mage. I.ex. then signing dev.application and dev.dll.manifest the property codebase is set to, for our case, un incorrect value.

**Describe the solution you'd like**
Either have a flag disabling call to mage or perhaps better add parameters to sign that are forwarded to the mage-call 

**Describe alternatives you've considered**
We have to call mage again for only the application file and then resign the application file again

**Comment by dtivel** [comment]
@klamfeldt, thanks for the report.

Can you provide more detail?

* What version of Sign CLI are you using?  You can view the version by executing in a command prompt:  `sign --version`
* What is the expected result and the actual result?
* Can you share a simple repro that demonstrates incorrect output from Mage?

**Comment by dtivel** [comment]
Please reactivate if you have more information.
