### ISSUE TITLE
Allow specifying multiple space separated files to sign

### ISSUE THREAD

**Issue by Daniel-Svensson** [dotnet/sign#685]
**Is your feature request related to a problem? Please describe.**

I want to use `dotnet sign` to batch sign files when using `velopack` installer.
That means that it must support multiple files one after each other on the command prompt (space separated)

Based on the current helt `sign code azure-key-vault <file(s)> [options]` i expected that I could just specify several files after each other, but it does not work and I get `Unrecognized command or argument '"file2.exe"'.` when I specify more that 1 file

**Describe the solution you'd like**

I want to be able to call dotnet sign using the following syntax
`sign code azure-key-vault "file1" "file2.exe" "file3.exe" --option1`
`sign code azure-key-vault --option1 file1 file 2 file3 `

**Describe alternatives you've considered**

don't do batch signing, use another tool

**Additional context**
Include the output of sign --version.

```
dotnet sign --version
0.9.1-beta.24170.3+394fc50bebb3ddaa3f79fc975f552d4ea2787552
```

It seems dotnet sign uses System.CommandLine? if so then according to [the documentation](https://learn.microsoft.com/en-us/dotnet/standard/commandline/define-commands#multiple-arguments)  it might be possible to set [Option.AllowMultipleArgumentsPerToken](https://learn.microsoft.com/en-us/dotnet/api/system.commandline.option.allowmultipleargumentspertoken#system-commandline-option-allowmultipleargumentspertoken) to true for the files argument.

**Comment by clairernovotny** [comment]
Sign CLI already supports globs; this can be done today with a glob pattern like `*.exe` or any other standard glob pattern.

**Comment by dtivel** [comment]
If this is still an issue, please reactivate with additional detail.

**Comment by hmz** [comment]
`sign code azure-key-vault "file1" "file2.exe" `
Fails with 
`Unrecognized command or argument '"file2.exe"'.`

when I specify more that 1 file

**Comment by hmz** [comment]
@clairernovotny @dtivel can you reopen this issue?
