### ISSUE TITLE
VSIX signing: Wrong docs with invalid syntax 

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/sign#744]
https://learn.microsoft.com/en-us/visualstudio/extensibility/dotnet-sign-cli-reference-vsix?view=vs-2022

https://learn.microsoft.com/en-us/visualstudio/extensibility/signing-vsix-packages?view=vs-2022

Looks like the commands were never verified...

**Comment by ErikEJ** [comment]
Also advice on finding the value for the "-k" parameter would be useful, like this: https://www.sysadmins.lv/blog-en/certutil-tips-and-tricks-query-cryptographic-service-providers-csp-and-ksp.aspx

**Comment by javierdlg** [comment]
@ErikEJ I'm doing a pass on the commands but is there one in specific you're having trouble running?

**Comment by javierdlg** [comment]
I've opened a new PR to add a bit more context on CSP and Key container values:
https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/12870

**Comment by ErikEJ** [comment]
@javierdlg Thanks for reaching out, highly appreciated.

I already did two PRs (one approved, the other not) https://github.com/MicrosoftDocs/visualstudio-docs/pulls?q=is%3Apr+author%3AErikEJ+with some basic syntax error updates.

The link to your new PR is broken - and I cannot see any in the vs-docs repo.

Basically, I had this command previously:

`.\vsixsigntool.exe sign /f C:\temp\cert.p7b /csp "SimplySign CSP" /k DEED...2B90D /sha1 e6...10 /fd sha256 /t http://time.certum.pl "EF Core Power Tools v2.6.66.vsix"
`
And this is my new command:

`sign code certificate-store -cfp 0FC..E9551 -k DEED...2B90D -csp "SimplySign CSP" -t http://time.certum.pl "EF Core Power Tools v2.6.414.vsix" -fl fileslist.txt`

So a guide for migrating to `sign code certificate-store` from `vsixsigntool.exe sign` would have been very helpful.

I notice for example:

the /k / -k value remains (but it was hard to pull out, so a guide for doing that would be very helpful)

/f and /fd is no longer needed

/sha1 is removed, and the -cfp value is completely different, (appreciate the guide for finding that)

-fl 
It is my understanding that vsixsigntool only signed the .vsix file, not contents inside. With 'sign code' every .dll inside is signed unless you provide a file list.

Hope this is useful feedback.

**Comment by javierdlg** [comment]
Thanks for your feedback @ErikEJ, this is very helpful. 

Seems like the PR is private so you can't see it, but I added steps to acquire your CSPs and other details you suggested. 
A guide for migrating is a great suggestion and I've added it to our backlog of tasks.

**Comment by ErikEJ** [comment]
@javierdlg Still see no information on the -k parameter, but here we go (and thanks for the powershell command to the the -cfp value)

`certutil -user -store my "<certificate serial number>"`
