### ISSUE TITLE
Bug: Incomplete PowerShell module signing support

### ISSUE THREAD

**Issue by MichaelGrafnetter** [dotnet/sign#769]
**Describe the bug**
Although the tool can sign PowerShell script files (`*.ps1` and `*.psm1`) with Azure Trusted Signing, support for additional extensions used by PowerShell (`*.psd1` and `*.ps1xml`) seems to be missing. As a result, PowerShell modules containing manifests and format definitions cannot be digitally signed by this tool.

**Repro steps**
```bat
sign code trusted-signing
        **/*.ps*1
        --trusted-signing-endpoint "${{ secrets.SIGNING_ENDPOINT }}"
        --trusted-signing-account "${{ secrets.SIGNING_ACCOUNT_NAME }}"
        --trusted-signing-certificate-profile "${{ secrets.SIGNING_PROFILE_NAME }}"
        --file-digest SHA256
        --timestamp-digest SHA256
        --timestamp-url "http://timestamp.acs.microsoft.com"
        --verbosity Information
```

**Expected behavior**
All `*.psm1` and `*.psd1` files should get digitally signed.

**Actual behavior**
Only `*.psm1` files get signed, while `*.psd1` files are ignored.

**Suggested resolution**
The issue might simply be resolved by adding `*.psd1` and `*.ps1xml` to the list of supported extensions in the [AzureSignToolSigner.cs](https://github.com/dotnet/sign/blob/04303f6df1622299042fb28f6060fd073ccd2dd6/src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs) file.

**Additional context**
Sign version 0.9.1-beta.24469.1+5516908609085978174904945d54144c117041dc

**Comment by dtivel** [comment]
@MichaelGrafnetter, https://www.nuget.org/packages/sign/0.9.1-beta.24529.1 has the fix.

Signing .xaml files is currently unsupported.  https://github.com/dotnet/sign/issues/778

**Comment by MichaelGrafnetter** [comment]
Thanks @dtivel, good work! I completely missed the remaining 2 extensions used by Powershell.
